<?php
/**
 *
 * Member Card Module for SMember Plugin SLiMS
 * Standard Version
 *
 * Copyright (C) 1431 H / 2010 M - Indra Sutriadi Pipii (indra.sutriadi@gmail.com)
 *
 * @file: index.php
 * @desc: member card page
 *
 */

$level = '../../../../../../';
require $level . 'sysconfig.inc.php';

require SENAYAN_BASE_DIR.'admin/default/session.inc.php';
require SENAYAN_BASE_DIR.'admin/default/session_check.inc.php';

$can_read = utility::havePrivilege('plugins', 'r');

if (!$can_read)
	die('<div>You dont have enough privileges to view this section</div>');

require('../../../conf.php');
require('../../../func.php');

checkip($conf);
checken();
checkref();

$plugin = checkname();

require '../../conf/card.conf.php';

$faktor = 37.795275591;
if ( ! $cardconf['idcard_member'])
	die('<div>No configuration founded!</div>');

extract($cardconf['idcard_member']);

$lebar = $lebar * $faktor;
$tinggi = $tinggi * $faktor;
$pasfoto_x = $pasfoto_lebar;
$pasfoto_lebar = $pasfoto_lebar * $faktor;
$pasfoto_y = $pasfoto_tinggi;
$pasfoto_tinggi = $pasfoto_tinggi * $faktor;

$ua = strtolower($_SERVER['HTTP_USER_AGENT']);
$css_dir = preg_match("/windows/i", $ua) ? "_win" : "_linux";
$css_dir = "./css/$css_dir/";

if (! empty($nip_pejabat_stempel))
	$pejabat_stempel = "<u>".$pejabat_stempel."</u><br />".$nip_prefix_stempel.$nip_pejabat_stempel;
else
	$pejabat_stempel = $pejabat_stempel . "<br />&nbsp;";

$criteria = "member_id,
	member_name,
	IF (gender = 1, 'Pria', 'Wanita') AS gender,
	m_type.member_type_name AS m_type,
	IF (member_address = '', '-', member_address) AS member_address,
	IF (member_email = '', '-', member_email) AS member_email,
	IF (postal_code = '', '-', postal_code) AS postal_code,
	IF (inst_name = '', '-', inst_name) AS inst_name,
	IF (member_phone = '', '-', member_phone) AS member_phone,
	member_image,
	DATE_FORMAT(register_date, '%d-%m-%Y') AS register_date,
	DATE_FORMAT(expire_date, '%d-%m-%Y') AS expire_date";
$tbon = "member, mst_member_type AS m_type";

if ($_POST['members'])
{
	$itemid = $_POST['members'];
	echo "<html>"
			."<head>"
				."<title>Kartu Member Generated By SMember</title>"
				."<script type=\"text/javascript\" src=\"./js/card.js\"></script>"
				."<link href=\"./css/card.css\" rel=\"stylesheet\" type=\"text/css\" />"
			."</head>"
			."<body onload=\"reload('$gaya','$css_dir');\">"
			."<!--awal kartu -->";

	$cssdir = $css_dir;
	$styles = scandir($cssdir);
	sort($styles);
	$options = '';
	foreach ($styles as $style)
	{
		$selected = $style == $gaya ? 'selected' : '';
		if ($style != "." AND $style != ".." AND is_dir($cssdir . "/" . $style))
			$options .= "<option $selected value=\"$style\">$style</option>";
	}
	$selector = "<div id=\"selector\" style=\"padding: 0 10px;\">"
			."<p>"
				."<label for=\"style\" style=\"padding-right: 2px;\">Pilih tampilan kartu:</label>"
				."<select id=\"style\" onchange=\"reload(this.value, '$css_dir')\">"
					.$options
				."</select>"
				."&nbsp;"
				."<label for=\"sided\" style=\"padding: 0 2px;\">Tampilkan sisi belakang?</label>"
				."<input id=\"sided\" type=\"checkbox\" onclick=\"checkside(this)\" /> Ya!"
			."</p>"
		."</div>";
	echo $selector;

	$pasfoto_blank = "<div style=\"width: $pasfoto_lebar; height: $pasfoto_tinggi; \" class=\"img_member_blank img_border\"><span style=\"vertical-align: middle;\">Pasfoto<br />$pasfoto_x x $pasfoto_y cm</span></div>";
	$pasfoto_blank2 = "<div style=\"width: $pasfoto_lebar; height: $pasfoto_tinggi;\" class=\"img_member_blank img_border_blank\"><img src=\"../../person/blank.png\" width=\"$pasfoto_lebar\" height=\"$pasfoto_tinggi\"></div>";

	$number = 1;
	foreach($itemid as $index => $value)
	{
		$barcode_text = $value;
		$query = $dbs->query("SELECT $criteria FROM $tbon WHERE member_id = '$barcode_text' AND m_type.member_type_id = member.member_type_id");
		$array = $query->fetch_assoc();

		// moindoi kon logo aka potakin atau dia
		$src_logo = $logo === TRUE ? "../../images/logos/$path_logo" : '../../images/logos/blank.png';
		$src_stamp = $gambar_stempel === TRUE ? "../../images/stamps/$path_stempel" : '../../images/stamps/blank.png';

		// moindoi kon pas foto member
		if ($array['member_image'] != NULL AND $pasfoto === true)
		{
			$props = getimagesize(IMAGES_BASE_DIR . "persons/" . $array['member_image']);
			if ($props[0] <= $pasfoto_lebar AND $props[1] <= $pasfoto_tinggi)
				$content_pasfoto = "<div style=\"width: $pasfoto_lebar; height: $pasfoto_tinggi;\" class=\"img_member img_border_trans\"><img src=\"".IMAGES_BASE_DIR."persons/".$array['member_image']."\" /></div>";
			else
				$content_pasfoto = "<div style=\"width: $pasfoto_lebar; height: $pasfoto_tinggi;\" class=\"img_member img_border_trans\"><img src=\"./lib/patch-thumb.php?lebar=$pasfoto_lebar&tinggi=$pasfoto_tinggi&src=". IMAGES_BASE_DIR ."persons/".$array['member_image']."\" /></div>";
		}
		else if ($array['member_image'] == NULL AND $pasfoto === true)
			$content_pasfoto = $pasfoto_blank;
		else
			$content_pasfoto = $pasfoto_blank2;

		// moindoi kon kode bar
		if ($kodebar === true)
		{
			$bar_img = "http://" . $_SERVER['SERVER_NAME']
				. MODPLUGINS_WEB_ROOT_DIR
				. $plugin
				. "/lib/phpbarcode/barcode.php?lihat=1&code=$barcode_text&encoding=".$encbar."&scale=1&mode=png";
			//~ echo "$bar_img";
			$bars = getimagesize($bar_img);
			//print_r($bars);
			$bars_x = $bar_rotate != 0 ? $lebar : $bars[0];
			$bars_y = $bars[1] - (1 * $faktor);
			$bar_img = urlencode($bar_img);
			$bar_rotate = $bar_rotate != 0 ? $bar_rotate : 0;
			$src_barcode = "./lib/patch-crop.php?lebar=$bars_x&tinggi=$bars_y&rotasi=$bar_rotate&src=$bar_img";
		}
		else
			$src_barcode = "./lib/blankbar.png";

		// moindoi kon stempel
		if ($stempel === true)
		{
			$div_stamp = "<div class=\"stamp_div\">"
				."<div class=\"gambar_stamp\"><img class=\"\" src=\"$src_stamp\" /></div>"
				."<p class=\"stamp lokasi_stamp\">$lokasi_stempel, $tanggal_stempel</p>"
				."<p class=\"stamp jabatan_stamp\">$jabatan_stempel</p>"
				."<p class=\"stamp pejabat_stamp\">$pejabat_stempel</p>"
			."</div>";
		} else $div_stamp = '';

		// moindoi kon kop
		if ($kop === true)
		{
			$div_heading = "<div class=\"heading_div\">";
			if ( ! empty($nama_perpustakaan)) $div_heading .= "<h1>$nama_perpustakaan</h1>";
			if ( ! empty($alamat_perpustakaan)) $div_heading .= "<h3>$alamat_perpustakaan</h1>";
			$div_heading .= "<hr /></div>";
		} else $div_heading = '';

		// mopotuot kon ibanya
		$div_other = "<div id=\"identitas\" class=\"other_div\">";
		if (in_array('member_id', $fields)) $div_other .= "<p class=\"p_id\"><label class=\"judul_label\">ID</label><span></span>". $array['member_id'] ."</p>";
		if (in_array('member_name', $fields)) $div_other .= "<p class=\"p_nama\"><label class=\"judul_label\">Nama</label><span></span>". $array['member_name'] ."</p>";
		if (in_array('gender', $fields)) $div_other .= "<p class=\"p_kelamin\"><label class=\"judul_label\">Kelamin</label><span></span>". $array['gender'] ."</p>";
		if (in_array('member_type_id', $fields)) $div_other .= "<p class=\"p_type\"><label class=\"judul_label\">Jenis</label><span></span>". $array['m_type'] ."</p>";
		if (in_array('postal_code', $fields)) $div_other .= "<p class=\"p_kodepos\"><label class=\"judul_label\">Kode Pos</label><span></span>". $array['postal_code'] ."</p>";
		if (in_array('inst_name', $fields)) $div_other .= "<p class=\"p_inst\"><label class=\"judul_label\">Institusi</label><span></span>". $array['inst_name'] ."</p>";
		if (in_array('member_phone', $fields)) $div_other .= "<p class=\"p_telp\"><label class=\"judul_label\">No. Telp</label><span></span>". $array['member_phone'] ."</p>";
		if (in_array('member_email', $fields)) $div_other .= "<p class=\"p_email\"><label class=\"judul_label\">Email</label><span></span>". $array['member_email'] ."</p>";
		if (in_array('register_date', $fields)) $div_other .= "<p class=\"p_expire\"><label class=\"judul_label\">Masa Berlaku</label><span></span>". $array['register_date'] ." s/d " . $array['expire_date']. "</p>";
		if (in_array('member_address', $fields)) $div_other .= "<p class=\"p_alamat\"><label class=\"judul_label\">Alamat</label><span></span><span class=\"label_alamat\">". nl2br($array['member_address']) ."</span></p>";
		$div_other .= "</div>";

		echo "<div class=\"container\">";
		echo "<div id=\"card_$number\" class=\"bg_first\">"
				."<div class=\"filter\" style=\"width: $lebar; height: $tinggi\">"
					."<div id=\"pre0\"></div>"
					."<div id=\"pre1\"></div>"
					."<div id=\"pre2\"></div>"
					."<div id=\"pre3\"></div>"
					."<div id=\"pre4\"></div>"
					."<img class=\"img_logo\" src=\"$src_logo\" />"
					.$content_pasfoto
					."<div id=\"barcode\"><img class=\"img_barcode\" alt=\"$barcode_text\" title=\"$barcode_text\" src=\"$src_barcode\" /></div>"
					.$div_stamp
					.$div_heading
					.$div_other
					."<div id=\"sep0\"></div>"
					."<div id=\"sep1\"></div>"
					."<div id=\"sep2\"></div>"
					."<div id=\"sep3\"></div>"
					."<div id=\"sep4\"></div>"
					."<div id=\"sep5\"></div>"
					."<div id=\"sep6\"></div>"
					."<div id=\"sep7\"></div>"
					."<div id=\"sep8\"></div>"
					."<div id=\"sep9\"></div>"
				."</div>"
			."</div>";

		if ($ganda === true)
		{
			// moindoi kon kop
			if ($kop_ganda === true)
			{
				$div_heading = "<div class=\"heading_div_b\">";
				if ( ! empty($nama_perpustakaan)) $div_heading .= "<h1>$nama_perpustakaan</h1>";
				if ( ! empty($alamat_perpustakaan)) $div_heading .= "<h3>$alamat_perpustakaan</h1>";
				$div_heading .= "<hr /></div>";
			} else $div_heading = '';
			
			$src_logo_ganda = $logo_ganda === TRUE ? "../../images/logos/$path_logo" : '../../images/logos/blank.png';

			// moindoi kon stempel
			if ($stempel_ganda === true)
			{
				$div_stamp = "<div class=\"stamp_div_b\">"
						."<div class=\"gambar_stamp\"><img class=\"\" src=\"$src_stamp\" /></div>"
						."<p class=\"stamp lokasi_stamp\">$lokasi_stempel, $tanggal_stempel</p>"
						."<p class=\"stamp jabatan_stamp\">$jabatan_stempel</p>"
						."<p class=\"stamp pejabat_stamp\">$pejabat_stempel</p>"
					."</div>";
			} else $div_stamp = '';

			$backside = "<div class=\"bg_second\">"
					."<div class=\"filter\" style=\"width: $lebar; height: $tinggi\">"
						."<div id=\"pre10\"></div>"
						."<div id=\"pre11\"></div>"
						."<div id=\"pre12\"></div>"
						."<div id=\"pre13\"></div>"
						."<div id=\"pre14\"></div>"
						.$div_heading
						."<img class=\"img_logo_b\" src=\"$src_logo_ganda\" />"
						.$div_stamp
						."<div class=\"other_div_b\">$isiganda</div>"
						."<div id=\"sep10\"></div>"
						."<div id=\"sep11\"></div>"
						."<div id=\"sep12\"></div>"
						."<div id=\"sep13\"></div>"
						."<div id=\"sep14\"></div>"
					."</div>"
				."</div>";
		}
		echo "</div>";

		if ($number % $perhal == 0)
			echo "<span style=\"page-break-before: always;\"></span>";

		$number ++;
	}

	echo "<!-- akhir kartu -->"
			."<div id=\"backside\" style=\"display:none;\">"
				.$backside
			."</div>"
		."</body>"
	."</html>";
}
else exit();
